### ISSUE TITLE
what url to add the urlhost using instagram login?

### ISSUE THREAD

**Issue by VinothKrishnanB** [junaid04/InstagramLogin#1]
Here is the code 

 func webView(_ webView: UIWebView, shouldStartLoadWith request: URLRequest, navigationType: UIWebViewNavigationType) -> Bool {
        
        
        let url = request.url!
        print(url.host!)
        if url.host! == "api.instagram.com" {
            indicator.startAnimating()
            if url.absoluteString.range(of: "code") != nil {
                // Extract the authorization code.
                let urlParts = url.absoluteString.components(separatedBy: "?")
                let code = urlParts[1].components(separatedBy: "=")[1]
                
                requestForAccessToken(code)
            }
            
        }
        
        return true
    }

i dont know what i missed in this code?
help me

**Comment by junaid04** [comment]
in url host check you redirect url 

here is my url
let redirectURL = "https://com.ajk.demo/"
and check for url.host = "com.ajk.demo"

check your redirect url
let url = request.url!
print(url.host!)

**Comment by VinothKrishnanB** [comment]
Hi 
I keep the code in xcode but is not working for me!!!!!

plz explain it

**Comment by junaid04** [comment]
did you create app in instagram?

**Comment by VinothKrishnanB** [comment]
yes brother i created Instagram app with API and secretKey also
but how to work with these keys?
here code for Instagram API->. please check this....


    let redirectURI = "http://www.google.com"
    let authorizationEndPoint = "https://api.instagram.com/oauth/authorize/"
    let accessTokenEndPoint = "https://api.instagram.com/oauth/access_token/"

I will waiting for reply brother...

**Comment by junaid04** [comment]
ok so did you set your redirect uri in instagram app

**Comment by VinothKrishnanB** [comment]
ya brother. it will be go to google.com website

**Comment by VinothKrishnanB** [comment]
the redirect uri = "http://www.google.com"

**Comment by VinothKrishnanB** [comment]
how can i redirect the uri in app?

**Comment by junaid04** [comment]
set redirect uri to
let redirectURi = "https://yourbundleIdentifer/"

in my case let redirectURL = "https://com.ajk.demo/"

and then print you url.host

and then check
if url.host! == "yourPrintedHost" {
        indicator.startAnimating()
        if url.absoluteString.range(of: "code") != nil {
            // Extract the authorization code.
            let urlParts = url.absoluteString.components(separatedBy: "?")
            let code = urlParts[1].components(separatedBy: "=")[1]
            
            requestForAccessToken(code)
        }

**Comment by VinothKrishnanB** [comment]
k brother i will try this code once i done let you know
